export default interface PlayerProfile {
  seasonTotalsRegularSeason?: (SeasonTotalsRegularSeasonEntityOrSeasonTotalsPostSeasonEntityOrSeasonTotalsAllStarSeasonEntityOrSeasonTotalsPreseasonEntity)[] | null;
  careerTotalsRegularSeason?: (CareerTotalsRegularSeasonEntityOrCareerTotalsPostSeasonEntityOrCareerTotalsAllStarSeasonEntityOrCareerTotalsPreseasonEntity)[] | null;
  seasonTotalsPostSeason?: (SeasonTotalsRegularSeasonEntityOrSeasonTotalsPostSeasonEntityOrSeasonTotalsAllStarSeasonEntityOrSeasonTotalsPreseasonEntity)[] | null;
  careerTotalsPostSeason?: (CareerTotalsRegularSeasonEntityOrCareerTotalsPostSeasonEntityOrCareerTotalsAllStarSeasonEntityOrCareerTotalsPreseasonEntity)[] | null;
  seasonTotalsAllStarSeason?: (SeasonTotalsRegularSeasonEntityOrSeasonTotalsPostSeasonEntityOrSeasonTotalsAllStarSeasonEntityOrSeasonTotalsPreseasonEntity)[] | null;
  careerTotalsAllStarSeason?: (CareerTotalsRegularSeasonEntityOrCareerTotalsPostSeasonEntityOrCareerTotalsAllStarSeasonEntityOrCareerTotalsPreseasonEntity)[] | null;
  seasonTotalsCollegeSeason?: (SeasonTotalsCollegeSeasonEntity)[] | null;
  careerTotalsCollegeSeason?: (CareerTotalsCollegeSeasonEntity)[] | null;
  seasonTotalsPreseason?: (SeasonTotalsRegularSeasonEntityOrSeasonTotalsPostSeasonEntityOrSeasonTotalsAllStarSeasonEntityOrSeasonTotalsPreseasonEntity)[] | null;
  careerTotalsPreseason?: (CareerTotalsRegularSeasonEntityOrCareerTotalsPostSeasonEntityOrCareerTotalsAllStarSeasonEntityOrCareerTotalsPreseasonEntity)[] | null;
  seasonRankingsRegularSeason?: (SeasonRankingsRegularSeasonEntity)[] | null;
  seasonRankingsPostSeason?: (SeasonRankingsPostSeasonEntity)[] | null;
  seasonHighs?: (SeasonHighsEntityOrCareerHighsEntity)[] | null;
  careerHighs?: (SeasonHighsEntityOrCareerHighsEntity)[] | null;
  nextGame?: (NextGameEntity)[] | null;
}
export interface SeasonTotalsRegularSeasonEntityOrSeasonTotalsPostSeasonEntityOrSeasonTotalsAllStarSeasonEntityOrSeasonTotalsPreseasonEntity {
  playerId: number;
  seasonId: string;
  leagueId: string;
  teamId: number;
  teamAbbreviation: string;
  playerAge: number;
  gp: number;
  gs: number;
  min: number;
  fgm: number;
  fga: number;
  fgPct: number;
  fG3M: number;
  fG3A: number;
  fg3Pct: number;
  ftm: number;
  fta: number;
  ftPct: number;
  oreb: number;
  dreb: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  tov: number;
  pf: number;
  pts: number;
}
export interface CareerTotalsRegularSeasonEntityOrCareerTotalsPostSeasonEntityOrCareerTotalsAllStarSeasonEntityOrCareerTotalsPreseasonEntity {
  playerId: number;
  leagueId: string;
  teamId: number;
  gp: number;
  gs: number;
  min: number;
  fgm: number;
  fga: number;
  fgPct: number;
  fG3M: number;
  fG3A: number;
  fg3Pct: number;
  ftm: number;
  fta: number;
  ftPct: number;
  oreb: number;
  dreb: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  tov: number;
  pf: number;
  pts: number;
}
export interface SeasonTotalsCollegeSeasonEntity {
  playerId: number;
  seasonId: string;
  leagueId: string;
  organizationId: number;
  schoolName: string;
  playerAge: number;
  gp: number;
  gs: number;
  min: number;
  fgm: number;
  fga: number;
  fgPct: number;
  fG3M: number;
  fG3A: number;
  fg3Pct: number;
  ftm: number;
  fta: number;
  ftPct: number;
  oreb: number;
  dreb: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  tov: number;
  pf: number;
  pts: number;
}
export interface CareerTotalsCollegeSeasonEntity {
  playerId: number;
  leagueId: string;
  organizationId: number;
  gp: number;
  gs: number;
  min: number;
  fgm: number;
  fga: number;
  fgPct: number;
  fG3M: number;
  fG3A: number;
  fg3Pct: number;
  ftm: number;
  fta: number;
  ftPct: number;
  oreb: number;
  dreb: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  tov: number;
  pf: number;
  pts: number;
}
export interface SeasonRankingsRegularSeasonEntity {
  playerId: number;
  seasonId: string;
  leagueId: string;
  teamId: number;
  teamAbbreviation: string;
  playerAge: string;
  gp: string;
  gs: string;
  rankPgMin?: number | null;
  rankPgFgm?: number | null;
  rankPgFga?: number | null;
  rankFgPct?: number | null;
  rankPgFg3m?: number | null;
  rankPgFg3a?: number | null;
  rankFg3Pct?: number | null;
  rankPgFtm?: number | null;
  rankPgFta?: number | null;
  rankFtPct?: number | null;
  rankPgOreb?: number | null;
  rankPgDreb?: number | null;
  rankPgReb?: number | null;
  rankPgAst?: number | null;
  rankPgStl?: number | null;
  rankPgBlk?: number | null;
  rankPgTov?: number | null;
  rankPgPts?: number | null;
  rankPgEff?: number | null;
}
export interface SeasonRankingsPostSeasonEntity {
  playerId: number;
  seasonId: string;
  leagueId: string;
  teamId: number;
  teamAbbreviation: string;
  playerAge: string;
  gp: string;
  gs: string;
  rankPgMin: number;
  rankPgFgm: number;
  rankPgFga: number;
  rankFgPct: number;
  rankPgFg3m: number;
  rankPgFg3a: number;
  rankFg3Pct: number;
  rankPgFtm: number;
  rankPgFta: number;
  rankFtPct: number;
  rankPgOreb: number;
  rankPgDreb: number;
  rankPgReb: number;
  rankPgAst: number;
  rankPgStl: number;
  rankPgBlk: number;
  rankPgTov: number;
  rankPgPts: number;
  rankPgEff: number;
}
export interface SeasonHighsEntityOrCareerHighsEntity {
  playerId: number;
  gameId: string;
  gameDate: string;
  vsTeamId: number;
  vsTeamCity: string;
  vsTeamName: string;
  vsTeamAbbreviation: string;
  stat: string;
  statValue: number;
  statOrder: number;
  dateEst: string;
}
export interface NextGameEntity {
  gameId: string;
  gameDate: string;
  gameTime?: null;
  location: string;
  playerTeamId: number;
  playerTeamCity: string;
  playerTeamNickname: string;
  playerTeamAbbreviation: string;
  vsTeamId: number;
  vsTeamCity: string;
  vsTeamNickname: string;
  vsTeamAbbreviation: string;
}
