"use strict";

var blank = require("./util/blank");
var invert = require("lodash.invert");

var nbaToJsMap = blank({
  "Season": "season",
  "SeasonType": "seasonType",
  "LeagueID": "leagueId",
  "PlayerID": "playerId",
  "GraphStartSeason": "graphStartSeason",
  "GraphEndSeason": "graphEndSeason",
  "GraphStat": "graphStat",
  "asynchFlag": "asynchFlag",
  "IsOnlyCurrentSeason": "isOnlyCurrentSeason",
  "AllStarSeason": "allStarSeason",
  "MeasureType": "measureType",
  "PerMode": "perMode",
  "PlusMinus": "plusMinus",
  "PaceAdjust": "paceAdjust",
  "Rank": "rank",
  "Outcome": "outcome",
  "Location": "location",
  "Month": "month",
  "SeasonSegment": "seasonSegment",
  "DateFrom": "dateFrom",
  "DateTo": "dateTo",
  "OpponentTeamID": "opponentTeamId",
  "VsConference": "vsConference",
  "VsDivision": "vsDivision",
  "GameSegment": "gameSegment",
  "Period": "period",
  "LastNGames": "lastNGames",
  "GameScope": "gameScope",
  "PlayerExperience": "playerExperience",
  "PlayerPosition": "playerPosition",
  "StarterBench": "starterBench",
  "TeamID": "teamId",
  "GameID": "gameId",
  "Position": "position",
  "RookieYear": "rookieYear",
  "ContextMeasure": "contextMeasure",
  "gameDate": "gameDate",
  "DayOffset": "dayOffset",
  "StartPeriod": "startPeriod",
  "EndPeriod": "endPeriod",
  "RangeType": "rangeType",
  "StartRange": "startRange",
  "EndRange": "endRange",
  "ContextFilter": "contextFilter",
  "zone-mode": "zoneMode",
  "GroupQuantity": "groupQuantity",
  "pageNo": "pageNo",
  "rowsPerPage": "rowsPerPage",
  "SeasonID": "seasonId"
});

var jsToNbaMap = blank(invert(nbaToJsMap));

var nbaParams = blank({
  "Season": 1,
  "SeasonType": 1,
  "LeagueID": 1,
  "PlayerID": 1,
  "GraphStartSeason": 1,
  "GraphEndSeason": 1,
  "GraphStat": 1,
  "asynchFlag": 1,
  "IsOnlyCurrentSeason": 1,
  "AllStarSeason": 1,
  "MeasureType": 1,
  "PerMode": 1,
  "PlusMinus": 1,
  "PaceAdjust": 1,
  "Rank": 1,
  "Outcome": 1,
  "Location": 1,
  "Month": 1,
  "SeasonSegment": 1,
  "DateFrom": 1,
  "DateTo": 1,
  "OpponentTeamID": 1,
  "VsConference": 1,
  "VsDivision": 1,
  "GameSegment": 1,
  "Period": 1,
  "LastNGames": 1,
  "GameScope": 1,
  "PlayerExperience": 1,
  "PlayerPosition": 1,
  "StarterBench": 1,
  "TeamID": 1,
  "GameID": 1,
  "Position": 1,
  "RookieYear": 1,
  "ContextMeasure": 1,
  "gameDate": 1,
  "DayOffset": 1,
  "StartPeriod": 1,
  "EndPeriod": 1,
  "RangeType": 1,
  "StartRange": 1,
  "EndRange": 1,
  "ContextFilter": 1,
  "zone-mode": 1,
  "GroupQuantity": 1,
  "pageNo": 1,
  "rowsPerPage": 1
});

var jsParams = blank({
  "season": 1,
  "allStarSeason": 1,
  "seasonType": 1,
  "leagueId": 1,
  "measureType": 1,
  "perMode": 1,
  "plusMinus": 1,
  "paceAdjust": 1,
  "rank": 1,
  "outcome": 1,
  "location": 1,
  "month": 1,
  "seasonSegment": 1,
  "dateFrom": 1,
  "dateTo": 1,
  "opponentTeamId": 1,
  "vsConference": 1,
  "vsDivision": 1,
  "gameSegment": 1,
  "period": 1,
  "lastNGames": 1,
  "gameScope": 1,
  "playerExperience": 1,
  "playerPosition": 1,
  "starterBench": 1,
  "teamId": 1,
  "gameId": 1,
  "position": 1,
  "rookieYear": 1,
  "contextFilter": 1,
  "contextMeasure": 1,
  "zoneMode": 1,
  "groupQuantity": 1,
  "pageNo": 1,
  "rowsPerPage": 1
});

module.exports = {
  nbaParams: nbaParams,
  jsParams: jsParams,
  jsToNbaMap: jsToNbaMap,
  nbaToJsMap: nbaToJsMap
};