var extend = require( 'extend' );

var nbaParams = Object.freeze(
  extend( Object.create( null ), {
    "Season": 1,
    "AllStarSeason": 1,
    "SeasonType": 1,
    "LeagueID": 1,
    "MeasureType": 1,
    "PerMode": 1,
    "PlusMinus": 1,
    "PaceAdjust": 1,
    "Rank": 1,
    "Outcome": 1,
    "Location": 1,
    "Month": 1,
    "SeasonSegment": 1,
    "DateFrom": 1,
    "DateTo": 1,
    "OpponentTeamID": 1,
    "VsConference": 1,
    "VsDivision": 1,
    "GameSegment": 1,
    "Period": 1,
    "LastNGames": 1,
    "GameScope": 1,
    "PlayerExperience": 1,
    "PlayerPosition": 1,
    "StarterBench": 1,
    "TeamID": 1,
    "GameID": 1,
    "Position": 1,
    "RookieYear": 1,
    "ContextFilter": 1,
    "ContextMeasure": 1,
    "zone-mode": 1,
    "GroupQuantity": 1,
    "pageNo": 1,
    "rowsPerPage": 1
  })
);

var jsParams = Object.freeze(
  extend( Object.create( null ), {
  "season": 1,
  "allStarSeason": 1,
  "seasonType": 1,
  "leagueId": 1,
  "measureType": 1,
  "perMode": 1,
  "plusMinus": 1,
  "paceAdjust": 1,
  "rank": 1,
  "outcome": 1,
  "location": 1,
  "month": 1,
  "seasonSegment": 1,
  "dateFrom": 1,
  "dateTo": 1,
  "opponentTeamId": 1,
  "vsConference": 1,
  "vsDivision": 1,
  "gameSegment": 1,
  "period": 1 ,
  "lastNGames": 1,
  "gameScope": 1,
  "playerExperience": 1,
  "playerPosition": 1,
  "starterBench": 1,
  "teamId": 1,
  "gameId": 1,
  "position": 1,
  "rookieYear": 1,
  "contextFilter": 1,
  "contextMeasure": 1,
  "zoneMode": 1,
  "groupQuantity": 1,
  "pageNo": 1,
  "rowsPerPage": 1
  })
);

var twoWayMap = Object.freeze(
  extend( Object.create( null ), {
    "Season": "season",
    "season": "Season",
    "AllStarSeason": "allStarSeason",
    "allStarSeason": "AllStarSeason",
    "SeasonType": "seasonType",
    "seasonType": "SeasonType",
    "LeagueID": "leagueId",
    "leagueId": "LeagueID",
    "MeasureType": "measureType",
    "measureType": "MeasureType",
    "PerMode": "perMode",
    "perMode": "PerMode",
    "PlusMinus": "plusMinus",
    "plusMinus": "PlusMinus",
    "PaceAdjust": "paceAdjust",
    "paceAdjust": "PaceAdjust",
    "Rank": "rank",
    "rank": "Rank",
    "Outcome": "outcome",
    "outcome": "Outcome",
    "Location": "location",
    "location": "Location",
    "Month": "month",
    "month": "Month",
    "SeasonSegment": "seasonSegment",
    "seasonSegment": "SeasonSegment",
    "DateFrom": "dateFrom",
    "dateFrom": "DateFrom",
    "DateTo": "dateTo",
    "dateTo": "DateTo",
    "OpponentTeamID": "opponentTeamId",
    "opponentTeamId": "OpponentTeamID",
    "VsConference": "vsConference",
    "vsConference": "VsConference",
    "VsDivision": "vsDivision",
    "vsDivision": "VsDivision",
    "GameSegment": "gameSegment",
    "gameSegment": "GameSegment",
    "Period": "period",
    "period": "Period",
    "LastNGames": "lastNGames",
    "lastNGames": "LastNGames",
    "GameScope": "gameScope",
    "gameScope": "GameScope",
    "PlayerExperience": "playerExperience",
    "playerExperience": "PlayerExperience",
    "PlayerPosition": "playerPosition",
    "playerPosition": "PlayerPosition",
    "StarterBench": "starterBench",
    "starterBench": "StarterBench",
    "TeamID": "teamId",
    "teamId": "TeamID",
    "GameID": "gameId",
    "gameId": "GameID",
    "Position": "position",
    "position": "Position",
    "RookieYear": "rookieYear",
    "rookieYear": "RookieYear",
    "ContextFilter": "contextFilter",
    "contextFilter": "ContextFilter",
    "ContextMeasure": "contextMeasure",
    "contextMeasure": "ContextMeasure",
    "zone-mode": "zoneMode",
    "zoneMode": "zone-mode",
    "GroupQuantity": "groupQuantity",
    "groupQuantity": "GroupQuantity",
    "pageNo": "pageNo",
    "rowsPerPage": "rowsPerPage"
  })
);

var shotDefaults = Object.freeze(
  extend( Object.create( null ), {
    'Season': '2013-14',
    'SeasonType': 'Regular Season',
    'LeagueID': '00',
    'PlayerID': '0',
    'TeamID': '0',
    'GameID': '',
    'Outcome': '',
    'Location': '',
    'Month': '0',
    'SeasonSegment': '',
    'DateFrom': '',
    'DateTo': '',
    'OpponentTeamID': '0',
    'VsConference': '',
    'VsDivision': '',
    'Position': '',
    'RookieYear': '',
    'GameSegment': '',
    'Period': '0',
    'LastNGames': '0',
    'ContextFilter': '',
    'ContextMeasure': 'FG_PCT',
    'zone-mode': 'basic'
  })
);

var teamStatDefaults = Object.freeze(
  extend( Object.create( null ), {
    'Season': '2013-14',
    'AllStarSeason': '',
    'SeasonType': 'Regular Season',
    'LeagueID': '00',
    'MeasureType': 'Base',
    'PerMode': 'PerGame',
    'PlusMinus': 'N',
    'PaceAdjust': 'N',
    'Rank': 'N',
    'Outcome': '',
    'Location': '',
    'Month': '0',
    'SeasonSegment': '',
    'DateFrom': '',
    'DateTo': '',
    'OpponentTeamID': '0',
    'VsConference': '',
    'VsDivision': '',
    'GameSegment': '',
    'Period': '0',
    'LastNGames': '0',
    'GameScope': '',
    'PlayerExperience': '',
    'PlayerPosition': '',
    'StarterBench': ''
  })
);

var playerSplitsDefaults = Object.freeze(
  extend( Object.create( null ), {
    "Season": "2013-14",
    "SeasonType": "Playoffs",
    "LeagueID": "00",
    "PlayerID": "201142",
    "MeasureType": "Base",
    "PerMode": "PerGame",
    "PlusMinus": "N",
    "PaceAdjust": "N",
    "Rank": "N",
    "Outcome": "",
    "Location": "",
    "Month": "0",
    "SeasonSegment": "",
    "DateFrom": "",
    "DateTo": "",
    "OpponentTeamID": "0",
    "VsConference": "",
    "VsDivision": "",
    "GameSegment": "",
    "Period": "0",
    "LastNGames": "0"
  })
);


module.exports = {
  nbaParams: nbaParams,
  jsParams: jsParams,
  twoWayMap: twoWayMap,
  shotDefaults: shotDefaults,
  teamStatDefaults: teamStatDefaults
};
