#!/usr/bin/env node

var fs = require("fs");
var path = require("path");

var emptyArrStr = "[]";

var teamsPath = path.join(__dirname, "../data/teams.json");
fs.writeFileSync(teamsPath, emptyArrStr);

var playersPath = path.join(__dirname, "../data/players.json");
fs.writeFileSync(playersPath, emptyArrStr);
