#!/usr/bin/env node

var ep = require("../lib/endpoints");
var maps = require("../lib/maps");

var assign = require("object-assign");

var params = {};

Object.keys(ep).forEach(function (k) {
  assign(params, ep[k].defaults());
});

assign(params, maps.nbaParams());

console.log(Object.keys(params));