#!/usr/bin/env node

var fs = require( "fs" );
var path = require( "path" );

var get = require( "../lib/get" );
var util = require( "../lib/util" );
var getPlayers = require( "../lib/get-players" );

getPlayers().then( function ( playerInfo ) {
  var filePath = path.join( __dirname, "../data/players.json" );
  fs.writeFileSync( filePath, JSON.stringify( playerInfo ) );
});
