#!/usr/bin/env node

var fs = require( "fs" );
var path = require( "path" );

var util = require( "../lib/util" );
var playersInfo = require( "../lib/info-players" );

playersInfo().then( function ( players ) {
  var filePath = path.join( __dirname, "../data/players.json" );
  fs.writeFileSync( filePath, JSON.stringify( players ) );
});
