#!/usr/bin/env node

var fs = require("fs");
var path = require("path");

var updateTeamsInfo = require("../lib").updateTeamsInfo;

updateTeamsInfo(function (err, teams) {
  var filePath = path.join(__dirname, "../data/teams.json");
  fs.writeFileSync(filePath, JSON.stringify(teams, null, 2));
});
