#!/usr/bin/env node

var fs = require( "fs" );
var path = require( "path" );

require( "../lib/polyfills" );
var maps = require( "../lib/maps" );
var util = require( "../lib/util" );
var teamInfo = require( "../lib/info-teams" );

teamInfo().then( function ( teams ) {
  var filePath = path.join( __dirname, "../data/teams.json" );
  fs.writeFileSync( filePath, JSON.stringify( teams ) );
});
